### ISSUE TITLE
getting TypeError: bad operand type for unary ~: 'float'

### ISSUE THREAD

**Issue by peter1125** [verbal-autopsy-software/pyCrossVA#1]
when trying the sample run, here is an error message that I encounter:

~~~
TypeError: bad operand type for unary ~: 'float'
~~~

I have tested on two machines, and one machine seems to run fine, so I am guessing this may be an issue related to compatibility or version control.

**Comment by pkmitre** [comment]
Can you share information (OS, environment, etc.) on both the machine where you see the error and the machine where it’s running correctly? Thanks!

**Comment by peter1125** [comment]
Hi,

Both devices are macOS (Mojave 10.14.2)

The only difference I can find is in python:
Python 3.7.0 works, 3.6.1 is the one that does not work.

Best,
Peter

**Comment by peter1125** [comment]
Both devices are macOS (Mojave 10.14.2) 

The only difference I can find is in python:
Python 3.7.0 works, 3.6.1 is the one that does not work.
